id: P006850
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS16187
  title: རྫོགས་ཆེན་སྔོན་འགྲོའི་ཁྲིད་ཡིག
  author: ''
  volumes:
    efce9f3309a3469690476089a8a96b3a:
      image_group_id: I8LS16189
      title: ''
      volume_number: 1
      total_pages: 38
      base_file: v001.txt
